# version: '3.8'
services:
  postgres-DB:
    image: postgres:latest
    container_name: postgres-DB
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - backstage-network
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backstage:
    image: rawaabha/backstage:${IMAGE_TAG}
    networks:
      - backstage-network
    ports:
      - "3000:3000" 
    depends_on:
      - postgres-DB 
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-DB:5432/${POSTGRES_DB}
networks:
  backstage-network:
    driver: bridge

volumes:
  postgres-data:
